### ISSUE TITLE
Custom Plugin Issue

### ISSUE THREAD

**Issue by MatthewVita** [RupertJS/rupert#25]
I'm working on https://github.com/MatthewVita/rupert-plugin-knockout and am manually putting it in `/home/laptop/Projects/rupert-plugin-knockout-tests/node_modules/rupert-plugin-knockout`, but Rupert (using `bare.tgz`) doesn't seem to register it (nothing in vendors.js).

What am I doing wrong? What's the best way to test this (I'll update the new plugin creation wiki entry as I go).

**Comment by DavidSouther** [comment]
Is `rupert-plugin-knockout-tests` on Github?

You're installing it via `npm ln`?

**Comment by MatthewVita** [comment]
`rupert-plugin-knockout-tests` is not on github. All it is is me putting down bare.tgz, git cloning my knockout plugin to node_modules and checking `vendors.js`

**Comment by DavidSouther** [comment]
You're missing a step - https://github.com/RupertJS/rupert/wiki/Cookbook:-Creating-a-Rupert-Plugin#registering-custom-plugin

You should probably add `rupert-plugin-knockout` to the `rupert-plugin-knockout-tests`'s `package.json` `dependencies` field; run `npm ln` in `rupert-plugin-knockout`, and finally run `npm ln rupert-plugin-knockout` in `rupert-plugin-knockout-tests`. Then fix the docs so that those steps are more apparent :)

**Comment by MatthewVita** [comment]
That did the trick.

I appended instructions here: https://github.com/RupertJS/rupert/wiki/Cookbook:-Creating-a-Rupert-Plugin#as-an-npm-module
